# fly.toml app configuration file generated for abdiels-db on 2024-06-17T22:55:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'abdiels-db'
primary_region = 'ams'

[build]
  image = 'mysql:8'


[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1


# Add the following sections
[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "abdiels_db"
  MYSQL_USER = "non_root_user"